export const FONTS = {
    black: require('../assets/fonts/rocatwoblack.ttf'),
    blackItalic: require('../assets/fonts/rocatwoblack.ttf'),
    bold: require('../assets/fonts/rocatwoblack.ttf'),
    boldItalic: require('../assets/fonts/rocatwoblack.ttf'),
    extraBold: require('../assets/fonts/rocatwoblack.ttf'),
    extraBoldItalic: require('../assets/fonts/rocatwoblack.ttf'),
    extraLight: require('../assets/fonts/rocatwoblack.ttf'),
    extraLightItalic: require('../assets/fonts/rocatwoblack.ttf'),
    italic: require('../assets/fonts/rocatwoblack.ttf'),
    light: require('../assets/fonts/rocatwoblack.ttf'),
    lightItalic: require('../assets/fonts/rocatwoblack.ttf'),
    medium: require('../assets/fonts/rocatwoblack.ttf'),
    mediumItalic: require('../assets/fonts/rocatwoblack.ttf'),
    regular: require('../assets/fonts/rocatwoblack.ttf'),
    semiBold: require('../assets/fonts/rocatwoblack.ttf'),
    semiBoldItalic: require('../assets/fonts/rocatwoblack.ttf'),
    thin: require('../assets/fonts/rocatwoblack.ttf'),
    thinItalic: require('../assets/fonts/rocatwoblack.ttf'),
}
